### ISSUE TITLE
converting pdbx/mmcif files to a bca database

### ISSUE THREAD

**Issue by sahakyanhk** [rcedgar/reseek#12]
Hi, I am getting this error when trying to convert CIF files into a BCA database:

__________________________________________________________________________
reseek -convert 00000/ -bca 0.bca  -threads 48

reseek v1.2.i86linux64 [fcf2599]
(C) Copyright 2024 Robert C. Edgar

[convert 00000/]

chainreader2.cpp(167):

reseek -convert 00000/ -bca 0.bca -threads 48

---Fatal error---
Excessive looping in ChainReader2::GetNextLo1()
__________________________________________________________________________

The -convert with the same files but in pdb format works.

**Comment by rcedgar** [comment]
How many files in the directory? I'm guessing it's a large number in which case this is a bug caused an internal sanity check failing. As a work-around, you could try making a .files with pathnames of the CIF files

On the other hand it it is a small number and you can make a small test case I'll take a look -- please make a directory with small number (2?) .cif files & bash script to reproduce the error, then post a tar.gz file with this directory somewhere I can download it.

**Comment by sahakyanhk** [comment]
The directory contains 5000 files, but I got the same error with 100 files. It works with 5000 files if they are in pdb format. 
The attached archive contains two folders with pdb and cif files. To reproduce the error, simply run 

$reseek -convert 00000_cif/ -bca cif.bca  -threads 1

and this one should work
$reseek -convert 00000_pdb/ -bca pdb.bca  -threads 1


[00000.tar.gz](https://github.com/user-attachments/files/17383374/00000.tar.gz)

**Comment by rcedgar** [comment]
To fix bug add these lines immediately before the closing brace at the end of `cif.cpp`:
<pre>
	if (Chain != 0)
		Chains.push_back(Chain);
</pre>

**Comment by sahakyanhk** [comment]
Now getting an error when compiling. 

`python vcxproj_make.py` ends with "make done"  but there is no binary file in ../bin. 

I attached the full output in err.txt.


[err.txt](https://github.com/user-attachments/files/17387792/err.txt)

**Comment by rcedgar** [comment]
check `make.stderr`, sounds like the `../bin/ `directory doesn't exist
should probably start from source for a tagged release rather than current main branch

**Comment by sahakyanhk** [comment]
Alright, v1.2 works and the problem was solved. 
Many thanks for your help!
