### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by apcamargo** [rcedgar/reseek#14]
Hi @rcedgar 

I'm trying to add Reseek to Bioconda and I'm facing two issues: compilation fails in Clang (which is what Bioconda uses for macOS, but this is beyond the point here), and that the ARM build fails.

Apparently, the error when compiling for ARM has to do with `parasail.h` and `immintrin.h`, as this is the error message:

```
22:24:35 BIOCONDA INFO (OUT) $BUILD_PREFIX/bin/aarch64-conda-linux-gnu-c++ -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/reseek-2.0.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -ffast-math -march=native -O3 -DNDEBUG -fopenmp  -ffast-math -march=native -O3 -DNDEBUG -fopenmp -c -o o/parasail.o parasail.cpp
22:24:35 BIOCONDA INFO (OUT) In file included from parasail.cpp:2:
22:24:35 BIOCONDA INFO (OUT) parasail.h:10:10: fatal error: immintrin.h: No such file or directory
22:24:35 BIOCONDA INFO (OUT)    10 | #include <immintrin.h>
22:24:35 BIOCONDA INFO (OUT)       |          ^~~~~~~~~~~~~
22:24:35 BIOCONDA INFO (OUT) compilation terminated.
22:24:35 BIOCONDA INFO (OUT) make: *** [Makefile:270: o/parasail.o] Error 1
22:24:35 BIOCONDA INFO (OUT) 
22:24:35 BIOCONDA INFO (OUT) 
22:24:35 BIOCONDA INFO (OUT) ERROR -- make failed
```

For additional context, I also applied the following patch before compilation: https://github.com/bioconda/bioconda-recipes/blob/3897e8cb869a49c71c3036f7b8997d587a76b37b/recipes/reseek/arm_support.patch

I'm not really familiar with ARM (or C programming), so I'm wondering if this is something that could be solved by patching Reseek or if the problem is goes deeper than that.

Thanks!

**Comment by rcedgar** [comment]
This is a deep problem, unfortunately. Reseek uses x86-specific SIMD optimization in Parasail https://github.com/jeffdaily/parasail which are not supported / not portable to ARM (not sure which).

**Comment by apcamargo** [comment]
That's fine. Just wanted to double check with you.

Parasil is also what's causing the Clang problems (dfue to `aligned_alloc`). But I can try to figfure out how to solve this one.
