### ISSUE TITLE
fatal error: gitver.txt: No such file or directory

### ISSUE THREAD

**Issue by durrantmm** [rcedgar/reseek#2]
Hi, trying to install reseek on Ubuntu 20.04. Ran

```
cd src/
make
```

Got the error:

```
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/fileseqsource.o fileseqsource.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/getss.o getss.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/sscluster.o sscluster.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/trainer.o trainer.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/usage.o usage.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/linereader.o linereader.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/lockobj.o lockobj.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/mx.o mx.cpp
ccache g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/myutils.o myutils.cpp
myutils.cpp:1957:10: fatal error: gitver.txt: No such file or directory
 1957 | #include "gitver.txt"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:177: o/myutils.o] Error 1
```

**Comment by rcedgar** [comment]
work around is to create a file gitver.txt in the current directory with a string "TODO" (include quotes, any string is ok, intent was the short hash from most recent commit) My bad I put `gitver.txt `in `.gitignore` :-(

**Comment by rcedgar** [comment]
Workaround is committed in the latest release, there is a placeholder file `src/gitver.txt`.
What I really want is to automatically put the git short hash when make is run -- there doesn't seem to be a simple way to do this, absent a better idea I'll probably add a bash script with `git log --oneline | head -n 1 | cut "-d " -f1 > gitver.txt`, this would be run manually before `make` (ugly solution!).

**Comment by rcedgar** [comment]
Fixed by implementing build_linux.py and build_win.bash as wrappers for building, these scripts generate gitver.txt.

**Comment by EricDeveaud** [comment]
hello,

wrappers does not work with release archive. 

`echo '"1.1"' > src/gitver.txt ` allows to build

**Comment by rcedgar** [comment]
that avoids the error, but doesn't quite solve the problem because `src/gitver.txt` should to be the short hash of the commit

**Comment by EricDeveaud** [comment]
I prefer 1.1 instead of 
`work around is to create a file gitver.txt in the src/ directory containing just a string "TODO"` see above ;-)

**Comment by rcedgar** [comment]
the "official" solution is to run `src/build_linux.py` which re-generates `Makefile `& runs `make`, not sure if that works in current master branch but it does work in dev branch which will be merged back to master in the next day or two
