### ISSUE TITLE
problems/warnings with  compilation under MacOS

### ISSUE THREAD

**Issue by igortru** [rcedgar/reseek#3]
After some modifications, reseek can be successfully compiled for macOS

major issue:   original makefile is not working on MacOs.
 clang report flag -fopenmp is not supported.
 useful information on:
https://mac.r-project.org/openmp/

during compilation many annoying warnings about using unsafe sprintf ,  can be easily removed if replace to snprintf.

**Comment by rcedgar** [comment]
-fopenmp linker flag removed in release v1.2-beta (OMP is not used).

**Comment by igortru** [comment]
add --std=c++11 to

CXXFLAGS := $(CFLAGS) -O3 -ffast-math -march=native --std=c++11

dbsearcher.h
from
        atomic<uint> m_QPCacheHits. = 0;
        atomic<uint> m_QPCacheMisses = 0;
to
        atomic<uint> m_QPCacheHits{0};
        atomic<uint> m_QPCacheMisses{0};

eval_feature.cpp        
        const char *Name = FeatureName.c_str();        
from        
          ProgressLog("Feature %s (%u)\n", FeatureName, AlphaSize);
to
          ProgressLog("Feature %s (%u)\n", Name, AlphaSize);

**Comment by rcedgar** [comment]
Fixed, verified that action build_osx is working.
